baseURL = 'https://adilfayaz01.github.io/Blog/'
languageCode = 'en-us'
title = 'Blog'
theme= "PaperMod"


[params.homeInfoParams]
Title = "Hi there wave"
Content = "Can be Info, links, about..."

[[params.socialIcons]]
name = "github"
url = "<link>"

[[params.socialIcons]]
name = "Youtube"
url = "<link2>"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

