<<<<<<< HEAD
baseURL = 'https://fayasuddin.blog/'
=======
baseURL = 'https://fayasuddin.blog'
>>>>>>> 5256d16 (Added Some modificatios and blog)
languageCode = 'en-us'
title = 'Blog'
theme= "PaperMod"

[params.profileMode]
enabled = true
title = "Mohammed Fayasuddin"
subtitle = "Cloud Security Engineer"
imageUrl = "https://cdn.pixabay.com/photo/2021/03/02/01/07/cyberpunk-6061251_960_720.jpg"
imageTitle = "Action"
imageWidth = 180
imageHeight = 180

  [[params.profileMode.buttons]]
  name = "Blog"
  url = "/posts"

  [[params.socialIcons]]
  name = "Youtube"
  url = "<link>"

  [[params.socialIcons]]
  name = "Github"
  url = "<link2>"

  [[params.socialIcons]]
  name = "Linked"
  url = "<link2>"

[params]
  env = "production"
  author = "Fayasuddin"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

[cover]
  image = "https://cdn.pixabay.com/photo/2014/09/02/15/28/styggkarret-433688_960_720.jpg"
  alt = "Image"
  caption = "Image"
  relative = false
